#!/usr/bin/env bash
set -euo pipefail
export LC_ALL='C'
export LANG='C'
export IFS=$' \t\n'

readonly REPO_PATH="$(command git rev-parse --show-toplevel)"

### gitleaks ###
# Repo: https://github.com/zricethezav/gitleaks
readonly GITLEAKS_OPTS="--verbose --redact --pretty --uncommitted --repo-path=${REPO_PATH}"
readonly GITLEAKS_GLOBAL_CONF="${XDG_CONFIG_HOME:-"${HOME}/.config"}/gitleaks/gitleaks.toml"
# Ref: https://github.com/zricethezav/gitleaks/issues/352
if command -v gitleaks >/dev/null 2>&1 &&
    [[ "$(command git config --bool hooks.gitleaks)" == 'true' ]]; then
    echo 'Running pre-push to gitleaks check...'
    if [[ -f "${REPO_PATH}/.gitleaks.toml" ]] || [[ -f "${REPO_PATH}/gitleaks.toml" ]]; then
        eval command gitleaks "${GITLEAKS_OPTS}" --repo-config
    elif [[ -f "${GITLEAKS_GLOBAL_CONF}" ]]; then
        eval command gitleaks "${GITLEAKS_OPTS}" --config="${GITLEAKS_GLOBAL_CONF}"
    fi
fi

exit 0
