# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
---
matches:
  - trigger: ',id'
    replace: 'znppunfuv'
  - trigger: ',mail'
    replace: 'znppunfuv@protonmail.com'
  - trigger: ',gmail'
    replace: 'znppunfuv@gmail.com'
  - trigger: ',domain'
    replace: 'znppunfuv.com'

  # Dates
  - trigger: ',iso8601'
    replace: '{{iso8601}}'
    vars:
      - name: iso8601
        type: date
        params:
          format: '%+'
  - trigger: ',ctime'
    replace: '{{ctime}}'
    vars:
      - name: ctime
        type: date
        params:
          format: '%c'
  - trigger: ',date'
    replace: '{{date}}'
    vars:
      - name: date
        type: date
        params:
          format: '%F'
